const GetCommandLineApplicationExecutionContent = ({
    RENDER_BINARY_DIR_PATH,
    RENDER_ECOSYSTEM_DATA_PATH,
    RENDER_PKG_CONF_DIRNAME_METADATA,
    RENDER_DIRNAME_MINIMAL_NODEJS_DEPENDENCIES,
    RENDER_DIRNAME_CONFIGURATIONS_DIR
}) => 
`#!/bin/bash

ECOSYSTEM_DATA_PATH="${RENDER_ECOSYSTEM_DATA_PATH}"

REPOSITORY_PATH="$ECOSYSTEM_DATA_PATH/repos/$REPOSITORY_NAMESPACE"
ECOSYSTEM_DEFAULT="$ECOSYSTEM_DATA_PATH/${RENDER_DIRNAME_CONFIGURATIONS_DIR}/ecosystem-defaults.json"
NODEJS_DEPS_PATH="$ECOSYSTEM_DATA_PATH/${RENDER_DIRNAME_MINIMAL_NODEJS_DEPENDENCIES}"

PACKAGE_PATH="$REPOSITORY_PATH/$PACKAGE_REPO_PATH"
STARTUP_JSON="$REPOSITORY_PATH/$PACKAGE_REPO_PATH/${RENDER_PKG_CONF_DIRNAME_METADATA}/startup-params.json"

${RENDER_BINARY_DIR_PATH} --package "$PACKAGE_PATH" \
--startupJson "$STARTUP_JSON" \
--ecosystemDefault "$ECOSYSTEM_DEFAULT" \
--ecosystemData "$ECOSYSTEM_DATA_PATH" \
--nodejsProjectDependencies "$NODEJS_DEPS_PATH" \
--executableName "$EXEC_NAME" \
--supervisorSocket "$SUPERVISOR_SOCKET_PATH" \
--commandLineArgs "$*"
`

module.exports = GetCommandLineApplicationExecutionContent
